# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest ruff
    - name: Install package # Needed to make relative imports work properly
      run: |
        pip install -e .
    - name: Lint with ruff
      run: |
        ruff check --output-format=github .
      continue-on-error: true
    - name: Test with pytest
      run: |
        pytest

  build-macos:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        brew install kustomize
        python -m pip install --upgrade pip
        pip install pytest ruff
    - name: Install package # Needed to make relative imports work properly
      run: |
        pip install -e .
    - name: Lint with ruff
      run: |
        ruff check --output-format=github .
      continue-on-error: true
    - name: Test with pytest
      run: |
        pytest
